spring.application.name=elevator-system

# Elevator System Configuration
elevator.system.numberOfElevators=3
elevator.system.numberOfFloors=10
elevator.system.elevatorCapacity=10
elevator.system.floorTransitionTimeMs=1000
elevator.system.doorOpenCloseTimeMs=2000
elevator.system.doorStayOpenTimeMs=3000
elevator.system.elevatorTickIntervalMs=100

# Logging
logging.level.com.example.elevator_system=INFO

